
DROP TABLE IF EXISTS PROCS.FORMATIONELEVES
DROP SCHEMA IF EXISTS PROCS;
GO
IF NOT EXISTS ( SELECT  *
                FROM    sys.schemas
                WHERE   name = N'PROCS' )
    EXEC('CREATE SCHEMA [PROCS]');
GO
CREATE TABLE PROCS.FORMATIONELEVES
(
ID_ELEVE INT IDENTITY(1,1) PRIMARY KEY,
NOM_ELEVE VARCHAR(50) NOT NULL ,
NB_HEURES_COURS_INFO INT ,
CODE_FILIERE VARCHAR(10)
);
GO						
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Nguyen', 820 , 'SLAM ENC');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Robert', 530 , 'Ecole 42');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Rakoto', 650 , 'SLAM LARM');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Tandia', 820 , 'SLAM ENC');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Matmati', 750 , 'SISR ENC');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Diabate', 1200 , 'Ecole 42');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Poothapilai', 820 , 'SLAM ENC');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Limbada', 820 , 'SLAM ENC');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Raini', 670 , 'Ecole IPSI');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Coco', 820 , 'SLAM ENC');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Traore', 650 , 'SLAM TURG');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Pierrot', 800 , 'Ecole 42');
INSERT INTO PROCS.FORMATIONELEVES  VALUES ('Durand', 720 , 'SLAM MONT');

GO




