DROP TABLE IF EXISTS MERSOLEIL.CLIENT ;
DROP TABLE IF EXISTS MERSOLEIL.STUDIO ;
DROP TABLE IF EXISTS MERSOLEIL.LOCATION ;
DROP TABLE IF EXISTS MERSOLEIL.HISTOLOC ;
DROP SCHEMA IF EXISTS MERSOLEIL;
GO
IF NOT EXISTS ( SELECT  *
                FROM    sys.schemas
                WHERE   name = N'MERSOLEIL' )
    EXEC('CREATE SCHEMA [MERSOLEIL]');
GO

CREATE TABLE MERSOLEIL.CLIENT
(
NUMCLI INT NOT NULL PRIMARY KEY IDENTITY(1,1),
GENRECLI CHAR(1) NOT NULL ,
NOMCLI VARCHAR(60) NOT NULL,
PRENOMCLI VARCHAR(60),
RUECLI VARCHAR(60),
CPCLI VARCHAR(60),
VilleCli VARCHAR(60),
CA DECIMAL(10,2)
);
INSERT INTO MERSOLEIL.CLIENT VALUES('H','Robert','Tom','avenue Mer','06150','Cannes',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('F','Richard','Fanny','avenue du Casino','06150','Cannes',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('H','Dupond','Jean','avenue Republique','69002','Lyon',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('F','Khomry','Akima','avenue de Gaulle','69007','Lyon',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('F','Marie','Jeanne','avenue Italie','75013','Paris',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('F','Valkany','Patricia','avenue de Flandres','59260','Lille',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('H','Folnaref','Mickael','avenue Paul Bert','59800','Lille',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('H','Druel','Patrick','rue Al�sia','75014','Paris',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('H','Berrouk','Moiloud','avenue de la libert�','94300','Vincennes',0);
INSERT INTO MERSOLEIL.CLIENT VALUES('F','Poulain','Am�lie','avenue de la Bretagne','44100','Nantes',0);


CREATE TABLE MERSOLEIL.STUDIO
(
NumStu INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOMBAT VARCHAR(60) NOT NULL,
NbPlaces INT, 
PrixSaison DECIMAL(10,2), 
PrixHSaison DECIMAL(10,2), 
NumProp INT) ;
INSERT INTO MERSOLEIL.STUDIO VALUES('Les acacias',2,650,400,1);
INSERT INTO MERSOLEIL.STUDIO VALUES('Les chalets m�diterran�e',2,550,300,1);
INSERT INTO MERSOLEIL.STUDIO VALUES('Les pins de Rome',2,575,260,1);
INSERT INTO MERSOLEIL.STUDIO VALUES('Alcazar',3,630,320,2);
INSERT INTO MERSOLEIL.STUDIO VALUES('Les palmiers',4,700,420,2);


CREATE TABLE MERSOLEIL.LOCATION(
NumLoc INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
NumStu INT NOT NULL, 
NumCli INT NOT NULL, 
NumSem INT NOT NULL, 
REGLE BIT, 
PrixLoc DECIMAL(10,2));
INSERT INTO MERSOLEIL.LOCATION VALUES(1,3,15,1,400) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,3,16,1,400) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,3,25,1,650) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,3,26,1,650) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,3,38,1,400) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,3,39,1,400) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,8,42,1,400) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,8,43,1,400) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,10,46,1,400) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(1,10,47,1,400) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(2,4,15,1,300) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(2,4,16,1,300) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(2,4,30,1,550) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(2,4,42,1,300) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(2,4,43,1,300) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(2,5,31,1,550) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(2,5,32,1,550) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(2,5,33,1,550) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(3,5,15,1,260) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(3,5,16,1,260) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(3,5,39,1,260) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(3,5,40,1,260) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,4,20,1,630) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,4,21,1,630) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,6,27,1,630) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,6,28,1,630) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,6,29,1,630) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,6,30,1,630) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,7,42,1,320) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,7,43,1,320) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,8,31,1,630) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(4,8,32,1,630) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(5,9,26,1,700) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(5,9,27,1,700) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(5,9,28,1,700) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(5,9,29,1,700) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(5,10,30,1,700) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(5,10,31,1,700) ;
INSERT INTO MERSOLEIL.LOCATION VALUES(5,10,32,1,700) ;




CREATE TABLE MERSOLEIL.HISTOLOC(
ID_HISTOLOC INT NOT NULL PRIMARY KEY IDENTITY(1,1) ,
DateHisto DATE, 
Numloc INT,
NumSem INT, 
NumStu INT, 
NumCli INT, 
Regle BIT , 
PrixLoc DECIMAL(10,2)) ;

